[theme]
base = "dark"
primaryColor = "#5eead4"
backgroundColor = "#0b0b10"
secondaryBackgroundColor = "#151522"
textColor = "#e6e7ee"
font = "Inter, sans-serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[logger]
level = "info"
